version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform"
      - curl -O https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform_1.6.6_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  build:
    commands:
      - echo "Running terraform init"
      - terraform init
      - echo "Running terraform validate"
      - terraform validate
      - echo "Running terraform plan"
      - terraform plan

artifacts:
  files:
    - '**/*'
