name: DevSecOps CI/CD Workflow

on:
  push:
    branches: [ main ]

jobs:
  devsecops-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.6

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Apply (Auto-approve)
      run: terraform apply -auto-approve

    - name: Run tfsec (Terraform security scanner)
      uses: aquasecurity/tfsec-action@v1.0.0

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@v0.16.0
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Install kubectl
      run: |
        sudo apt-get update
        sudo apt-get install -y kubectl

    - name: Apply Sealed Secret
      env:
        KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
      run: |
        kubectl apply -f sealed-docker-auth.yaml

    - name: Deploy to Kubernetes
      env:
        KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
      run: |
        kubectl apply -f k8s/deployment.yaml
