name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  security-scans-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Run tfsec (Terraform security scanner)
        uses: aquasecurity/tfsec-action@v1.0.3

      - name: Run Trivy (Container vulnerability scanner)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_YAML }}" > $HOME/.kube/config

      - name: Apply Kubernetes Manifests
        run: kubectl apply -f k8s/

